// This file is automatically generated from your CSS. Any edits will be overwritten.
export const profile: string;
export const cardBody: string;
export const cardImage: string;
export const card: string;
